import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="antialiased">
				<ToastContainer theme="dark" />
				<main className="min-h-[calc(100vh-5rem)]">{children}</main>
			</body>
		</html>
	);
}
